name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push slim image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./slim/Dockerfile
        platforms: linux/amd64
        tags: engineers4cloud/containeros:slim-0.8.7
        push: true
        
    - name: Build and push base image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./base/Dockerfile
        platforms: linux/amd64
        tags: engineers4cloud/containeros:base-0.8.7
        push: true
        
    - name: Build and push java17 image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./java17/Dockerfile
        platforms: linux/amd64
        tags: engineers4cloud/containeros:java-17.0.3_7
        push: true    
